FROM  nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

WORKDIR /app
# Install Python 3.10
RUN apt-get update && apt-get install -y python3.10 python3.10-distutils && \
    apt-get install -y python3-pip && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 && \
    python3 -m pip install --upgrade pip \
    && apt-get update && apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev libgl1-mesa-glx

COPY   requirements.txt  requirements.txt
RUN pip install --no-cache  --no-cache-dir -r requirements.txt
COPY src/ src/